-- ================================================================
-- Full Mobile Legends hero list — source: liquipedia.net/mobilelegends
-- Run this in Supabase SQL Editor
-- ================================================================

INSERT INTO public.heroes (name, role) VALUES

  -- Tank
  ('Akai',           'tank'),
  ('Atlas',          'tank'),
  ('Barats',         'tank'),
  ('Baxia',          'tank'),
  ('Belerick',       'tank'),
  ('Carmilla',       'tank'),
  ('Chip',           'tank'),
  ('Edith',          'tank'),
  ('Franco',         'tank'),
  ('Fredrinn',       'tank'),
  ('Gatotkaca',      'tank'),
  ('Gloo',           'tank'),
  ('Grock',          'tank'),
  ('Hylos',          'tank'),
  ('Jawhead',        'tank'),
  ('Johnson',        'tank'),
  ('Khufra',         'tank'),
  ('Lolita',         'tank'),
  ('Minotaur',       'tank'),
  ('Tigreal',        'tank'),
  ('Uranus',         'tank'),

  -- Fighter
  ('Aldous',         'fighter'),
  ('Alpha',          'fighter'),
  ('Alucard',        'fighter'),
  ('Argus',          'fighter'),
  ('Arlott',         'fighter'),
  ('Aulus',          'fighter'),
  ('Badang',         'fighter'),
  ('Balmond',        'fighter'),
  ('Bane',           'fighter'),
  ('Chou',           'fighter'),
  ('Cici',           'fighter'),
  ('Dyrroth',        'fighter'),
  ('Freya',          'fighter'),
  ('Guinevere',      'fighter'),
  ('Hilda',          'fighter'),
  ('Julian',         'fighter'),
  ('Khaleed',        'fighter'),
  ('Lapu-Lapu',      'fighter'),
  ('Leomord',        'fighter'),
  ('Lukas',          'fighter'),
  ('Martis',         'fighter'),
  ('Masha',          'fighter'),
  ('Minsitthar',     'fighter'),
  ('Paquito',        'fighter'),
  ('Phoveus',        'fighter'),
  ('Roger',          'fighter'),
  ('Ruby',           'fighter'),
  ('Silvanna',       'fighter'),
  ('Sora',           'fighter'),
  ('Sun',            'fighter'),
  ('Terizla',        'fighter'),
  ('Thamuz',         'fighter'),
  ('X.Borg',         'fighter'),
  ('Yin',            'fighter'),
  ('Yu Zhong',       'fighter'),
  ('Zilong',         'fighter'),

  -- Mage
  ('Alice',          'mage'),
  ('Aurora',         'mage'),
  ('Cecilion',       'mage'),
  ('Chang''e',       'mage'),
  ('Cyclops',        'mage'),
  ('Esmeralda',      'mage'),
  ('Eudora',         'mage'),
  ('Faramis',        'mage'),
  ('Gord',           'mage'),
  ('Harith',         'mage'),
  ('Harley',         'mage'),
  ('Kadita',         'mage'),
  ('Kagura',         'mage'),
  ('Lunox',          'mage'),
  ('Luo Yi',         'mage'),
  ('Lylia',          'mage'),
  ('Nana',           'mage'),
  ('Novaria',        'mage'),
  ('Odette',         'mage'),
  ('Pharsa',         'mage'),
  ('Vale',           'mage'),
  ('Valentina',      'mage'),
  ('Valir',          'mage'),
  ('Vexana',         'mage'),
  ('Xavier',         'mage'),
  ('Yve',            'mage'),
  ('Zetian',         'mage'),
  ('Zhask',          'mage'),
  ('Zhuxin',         'mage'),

  -- Marksman
  ('Beatrix',        'marksman'),
  ('Brody',          'marksman'),
  ('Bruno',          'marksman'),
  ('Claude',         'marksman'),
  ('Clint',          'marksman'),
  ('Granger',        'marksman'),
  ('Hanabi',         'marksman'),
  ('Irithel',        'marksman'),
  ('Ixia',           'marksman'),
  ('Karrie',         'marksman'),
  ('Kimmy',          'marksman'),
  ('Layla',          'marksman'),
  ('Lesley',         'marksman'),
  ('Melissa',        'marksman'),
  ('Miya',           'marksman'),
  ('Moskov',         'marksman'),
  ('Natan',          'marksman'),
  ('Obsidia',        'marksman'),
  ('Popol and Kupa', 'marksman'),
  ('Wanwan',         'marksman'),
  ('Yi Sun-shin',    'marksman'),

  -- Assassin
  ('Aamon',          'assassin'),
  ('Benedetta',      'assassin'),
  ('Fanny',          'assassin'),
  ('Gusion',         'assassin'),
  ('Hanzo',          'assassin'),
  ('Hayabusa',       'assassin'),
  ('Helcurt',        'assassin'),
  ('Joy',            'assassin'),
  ('Karina',         'assassin'),
  ('Lancelot',       'assassin'),
  ('Ling',           'assassin'),
  ('Natalia',        'assassin'),
  ('Nolan',          'assassin'),
  ('Saber',          'assassin'),
  ('Selena',         'assassin'),
  ('Suyou',          'assassin'),

  -- Support
  ('Angela',         'support'),
  ('Diggie',         'support'),
  ('Estes',          'support'),
  ('Floryn',         'support'),
  ('Kaja',           'support'),
  ('Kalea',          'support'),
  ('Marcel',         'support'),
  ('Mathilda',       'support'),
  ('Rafaela',        'support')

ON CONFLICT (name) DO UPDATE SET role = EXCLUDED.role;
